# Server Configuration
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: aftas
  datasource:
    url: jdbc:mysql://localhost:3306/aftas?createDatabaseIfNotExist=true
    #url: jdbc:mysql://mysqldb:3306/aftas?createDatabaseIfNotExist=true # for docker with embedded mysql container
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

seeders:
  enabled: false
jwt:
  access:
    expirationInMs: 1440000 # 24 minutes
  refresh:
    expirationInMonths: 1
  signing:
    key: p5eHhtsr9qvSTaybbxGgYkhvnT7PYcqCxi6tNUEyXvQ=
users:
  default:
    password: $2a$12$DMj8nKER7YAx4Z3jVIFwZufkl64hfXdHZrYUbn20TH0VdfAC3p2CO # 1234 (bcrypt)

logging:
  level:
    org:
      springframework:
        security: trace
        web: trace
    liquibase: trace


