# Server Configuration
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/aftas?createDatabaseIfNotExist=true
    url: jdbc:mysql://mysqldb:3306/aftas?createDatabaseIfNotExist=true # for docker with embedded mysql container
    username: idder
    password: idderjamh
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
seeders:
  enabled: false
